### ISSUE TITLE
Create Repeating Events

### ISSUE THREAD

**Issue by leoselig** [hpi-swt2/event-und-raumplanung#116]
**As a user I want to create repeating events so that I do not have to create the same event for each occurance.**

![repeating events](https://cloud.githubusercontent.com/assets/3418034/5174604/f62e92c0-7432-11e4-9521-f6b690455338.jpg)

**Acceptance Criteria:**
- [x] Events can repeat weekly (on one or more days)
- [x] All occurances of the series must have the same event details (room, time, description, tasks, etc.)
- [x] Repititions are arranged upon creation/edition

**Tasks**
- [x] Install Gems (ice_cube, recurring_select)
- [x] Try both Gems with examples
- [x] Add a new field to Event model to store a schedule (hash / yaml ?)
- [x] Build a prototypic UI from the sketch displayed above
- [x] Store input from UI into Event model
- [x] Add GUI to update schedules
- [x] Provide API for Dashboard (next n events)
- [x] Provide API for Calendar (events from ... to ...)

**Comment by leoselig** [comment]
Split into #284
