### ISSUE TITLE
Decline Single Event Occurance (22 est.)

### ISSUE THREAD

**Issue by leoselig** [hpi-swt2/event-und-raumplanung#119]
**As a room responsible I want to decline a single event occurance so that I can react to unique events in the same room that are more important**

**Acceptance Criteria:**
- [ ] Declining a single occurance is possible via a button on the occurance page (see #198)
- [ ] Decline button is only visible to users that are allowed to manage approval for that event/room
- [ ] Declining a single occurance does not affect the general approval of the event
- [ ] Declined occurances do not show up in any event lists (dashboard calender, upcomings event, ...)
- [ ] Clicking Decline opens dialog asking whether series or occurance should be affected

**Tasks:**
- [x] Build dialog for asking"series or occurance"?
- [x] Build that dialog in HTML
- [x] API to decline SingleOccurrence by start time
- [x] Link Delete Button on EventOccurrence page to decline SingleOccurrence (custom route)
- [x] Securitycheck in OccurrenceController#destroy
- [x] Link Delete Button to Event destruction if whole series is chosen
- [x] Controller and model (single_occurrence_event?) tests

**Reminder:**
- [x] If can? :show

**Comment by numberpi** [comment]
@leoselig Shall declining an event occurrence trigger an activitiy log entry?

**Comment by leoselig** [comment]
Yes, good point, I'll update the AC accordingly
