### ISSUE TITLE
[3] Embedding Activity Log in Event View (3h est.)

### ISSUE THREAD

**Issue by mweisz** [hpi-swt2/event-und-raumplanung#272]
**As event creator I want to see the activity log related to a certain event directly on the event's page.**

- [x] The user interface and design should be adapted to the event view page
- [x] Embed activity log (as described in #120) into the event view
- [x] The activity log should be rendered in its own section (just like the tasks)
- [x] The activity log section is only visible to the event creator and the users added to the event admin list (as described in #121)
- [x] All functionality (as described in #120) should still be working.

**Excludes:** Actual implementation of activity log mechanism (already done by Team Biber). 

---

##### Conceptual Mockup
*Used only for illustrating the concept, __not__ the actual design.*

![eventseite](https://cloud.githubusercontent.com/assets/1974386/5770872/fa8955f2-9d32-11e4-9204-f16b052e25fb.png)

**Comment by leoselig** [comment]
I think this completely duplicates #120 
@mweisz ?

**Comment by mweisz** [comment]
@leoselig #120 is about the implementation of the activity log feature itself (as mentioned in the *remarks* section in this user story. This story was  about properly integrating it into the event's page (visibility, look and feel etc.). If the visibility aspect is already sufficiently covered in #121 this story should focus on the look-and-feel alone and I'll adjust the acceptance criteria accordingly. Is that ok?
