### ISSUE TITLE
[4] Menu Entries and UI Tweaks in Navigation (3h est.)

### ISSUE THREAD

**Issue by mweisz** [hpi-swt2/event-und-raumplanung#273]
**As a user I want to be able to navigate to the Room Properties and Group Permissions pages using the main navigation.**

- [x] There menu should now include a *Request* section (linking to /events_approval) only visible to users who have the permission to manage room requests
- [x] The menu should now include *Properties* (linking to /room_properties) in the configuration dropdown menu
- [x] The menu should now include *Print* (linking to /printoverview) in the configuration dropdown menu
- [x] The menu should now include *Templates* (linking to /templates) in the configuration dropdown menu
- [x] The menu should also include *Permissions* (linking to /permissions) in the configuration dropdown menu (last entry after groups).
- [x] The property entry visibility should be the same as for the *rooms* entry
- [x] Background colour for hovered menu items is #808080.
- [x] Background colour for dropdown menu is #808080.
- [x] Background colour for hovered dropdown menu items is #5a6065.

---

##### Conceptual Mockup
*Used only for illustrating the concept, __not__ the actual design.*

![bildschirmfoto 2015-02-04 um 10 17 46](https://cloud.githubusercontent.com/assets/1974386/6037808/b7c8d308-ac57-11e4-88f0-c1b139873db7.png)
