### ISSUE TITLE
Delete Single Event Occurance

### ISSUE THREAD

**Issue by leoselig** [hpi-swt2/event-und-raumplanung#320]
**As a user I want to delete a single occurance so that I do not have to cancel the whole series.**

**Acceptance Criteria:**
- [ ] Deleting a single occurance is possible via a button on the occurance page (see #198)
- [ ] Delete button is only visible to the event owner (and the admin) but **not**,  for instance, the room responsible
- [ ] Deleting a single occurance does not affect the general approval of the event
- [ ] Deleted occurances do not show up in any event lists (dashboard calender, upcomings event, ...)
- [ ] Clicking Delete opens dialog asking whether series or occurance should be affected

**Tasks:**
- [x] Build dialog for asking"series or occurance"?
- [x] Build that dialog in HTML
- [x] API to decline SingleOccurrence by start time
- [x] Link Delete Button on EventOccurrence page to decline SingleOccurrence (custom route)
- [x] Securitycheck in OccurrenceController#destroy
- [x] Link Delete Button to Event destruction if whole series is chosen
- [x] Controller and model (single_occurrence_event?) tests
- [x] Revoke exclusions in series when changing the event afterwards

**Reminder:**
- [x] If can? :show
