### ISSUE TITLE
[1] Task List (13h est.)

### ISSUE THREAD

**Issue by mweisz** [hpi-swt2/event-und-raumplanung#51]
**As a user I want to have a basic list of all _[tasks](https://github.com/hpi-swt2/event-und-raumplanung/wiki/Glossar#task)_ that are associated to a certain event.**
- [x] Tasks can be marked as done (directly from within the list view)
- [x] Newly created tasks are never marked as done
- [x] A task entry consists of the title and an indication of status (e.g. using a box)
- [x] Clicking a task redirects to the task's page
- [x] There is an add icon linking to a page where a new task can be created for the current event
- [x] The list is rendered in some kind of panel or box
- [x] The event (for which to show corresponding tasks) can be selected in a dropdown menu

---
##### Conceptual mockup

_Used only for illustrating the concept, **not** the actual design._
![tasklist basic](https://cloud.githubusercontent.com/assets/1974386/4943685/e1c2a712-65f6-11e4-82f9-90c4c929031d.png)
##### Remarks

Later on, the task list will most likely be embedded in a box or panel that is shown during event creation and editing and will not be displayed on a page of its own. Therefore please aim for a flexible and responsive layout/user interface.
