### ISSUE TITLE
[5] Task List in Dashboard (13h est.)

### ISSUE THREAD

**Issue by mweisz** [hpi-swt2/event-und-raumplanung#88]
**As a user I want my dashboard to include a list of all _[tasks](https://github.com/hpi-swt2/event-und-raumplanung/wiki/Glossar#task)_ that were previously assigned to me, such that I can get an overview of what remains to be done.**
- [x] The task list is rendered in some kind of panel or box
- [x] Only tasks whose assignment I accepted are listed
- [x] Tasks for events that are already passed are not listed
- [x] Tasks can be marked as done (directly from within the list view)
- [x] Tasks are grouped by the event they belong to
- [x] The event's title is displayed and a click redirects to the event's page 
- [x] A click on a task redirects to the task's page

---

Tasks:
- [x] Tests
- [x] locales
- [x] partial
- [x] filter event by date
- [x] filter tasks: user, accepted
- [x] group by event
- [x] redirect to event/task
- [x] mark as done

---
##### Conceptual mockup

_Used only for illustrating the concept, **not** the actual design._
![bildschirmfoto 2014-11-20 um 19 48 38](https://cloud.githubusercontent.com/assets/1974386/5130878/8a6c8fd4-70ee-11e4-95c1-9b6394324f21.png)
