### ISSUE TITLE
[9] Embedding Task List in Event View (8h est.)

### ISSUE THREAD

**Issue by mweisz** [hpi-swt2/event-und-raumplanung#92]
**As a user I want to be able to see the list of  _[tasks](https://github.com/hpi-swt2/event-und-raumplanung/wiki/Glossar#task)_ that are associated to a certain event embedded directly on the event's page.**
- [x] The task list ist rendered in some kind of box or panel
- [x] All functionality of a task list (as described in #51 [excluding the dropdown menu], #27, #43, #91 ) should still be available
- [x] The task list should only be visible on the event's show page (not during editing or creation)

---

Tasks:
- [x] tests
- [x] locales
- [x] embed partial
- [x] get data (controller)
- [x] correct redirect on "back" button

---
##### Conceptual mockup

_Used only for illustrating the concept, **not** the actual design._
![bildschirmfoto 2014-11-20 um 22 06 25](https://cloud.githubusercontent.com/assets/1974386/5132985/84cb758c-7101-11e4-8e03-425959e326fe.png)
